Repository First-Aid-Flutter-App/FirstAid, pull requests merged in 2024-09, with the labels that each got.

#1 feat(select screen): add cards
  lib/main.dart
  lib/models/situation.dart
  lib/screens/first_aid_steps_screen.dart
  lib/screens/situation_selection_screen.dart
  lib/widgets/situation_card.dart
  test/widget_test.dart
Labels: enhancement

#2 feat(info screen): add info
  lib/screens/situation_selection_screen.dart
  lib/screens/user_information_screen.dart
Labels: enhancement

#3 Tests
  integration_test/integration_test.dart
  pubspec.lock
  pubspec.yaml
  test/golden/counter_widget_test.dart
  test/golden/goldens/counter_widget_0.png
  test/golden/goldens/counter_widget_1.png
  test/mocking_test.dart
  test/mocking_test.mocks.dart
  test/unit_test.dart
  test/widget_test.dart
Labels: tests

#5 feat(navigation): add bottom navigation bar
  lib/main.dart
  lib/screens/cpr_guide_screen.dart
  lib/screens/main_screen.dart
  pubspec.yaml
Labels: enhancement

#6 feat(cpr screen): add cpr guide with timer
  assets/cpr_step_1.png
  assets/cpr_step_2.png
  assets/cpr_step_3.png
  lib/screens/cpr_guide_screen.dart
  lib/widgets/cpr_steps.dart
  lib/widgets/cpr_timer.dart
  pubspec.yaml
Labels: enhancement

#11 feat(l10n): add russian/english localization
  l10n.yaml
  lib/l10n/intl_en.arb
  lib/l10n/intl_ru.arb
  lib/l10n/l10n.dart
  lib/main.dart
  lib/screens/cpr_guide_screen.dart
  lib/screens/first_aid_steps_screen.dart
  lib/screens/main_screen.dart
  lib/screens/situation_selection_screen.dart
  lib/screens/user_information_screen.dart
  lib/widgets/cpr_timer.dart
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement

#10 refactor: replaced setState with riverpod state manager
  lib/main.dart
  lib/notifiers/cpr_timer_notifier.dart
  lib/notifiers/first_aid_steps_notifier.dart
  lib/providers/navigation_provider.dart
  lib/providers/situation_provider.dart
  lib/screens/first_aid_steps_screen.dart
  lib/screens/main_screen.dart
  lib/screens/situation_selection_screen.dart
  lib/widgets/cpr_timer.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#17 edit(heart painter): made CustomPainter for the heart animation
  lib/widgets/cpr_timer.dart
  lib/widgets/heart_painter.dart
Labels: refactor

#20 chore(readme)
  README.md
  demo/cpr.png
  demo/cpr2.png
  demo/firstaid.png
  demo/firstaid2.png
  demo/myhealth.png
Labels: documentation

#21 test: added new unit, widget, mocking and golden tests
  test/golden/counter_widget_test.dart
  test/golden/goldens/cpr_step_widget.png
  test/mocking_test.dart
  test/unit_test.dart
  test/widget_test.dart
Labels: tests
